import { RecipeListDto, RecipeDto } from "@/types/api";

export interface MockCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  recipeCount: number;
  imageUrl: string;
}

export const MOCK_CATEGORIES: MockCategory[] = [
  {
    id: "cat-1",
    name: "Món chính gia đình",
    slug: "mon-chinh",
    description: "Những món ăn ấm cúng, đậm đà chuẩn vị cơm nhà cho mâm cơm hàng ngày.",
    recipeCount: 42,
    imageUrl: "/images/image 1.png",
  },
  {
    id: "cat-2",
    name: "Món chay thanh tịnh",
    slug: "mon-chay",
    description: "Công thức món chay nhẹ nhàng, giàu dinh dưỡng từ rau củ tươi ngon.",
    recipeCount: 28,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "cat-3",
    name: "Bánh & Tráng miệng",
    slug: "banh-ngot",
    description: "Các món bánh ngọt nướng thủ công, chè truyền thống và món tráng miệng mát lạnh.",
    recipeCount: 35,
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "cat-4",
    name: "Đồ uống & Pha chế",
    slug: "do-uong",
    description: "Trà hoa quả giải nhiệt, cà phê chuẩn vị và các loại nước ép bổ dưỡng.",
    recipeCount: 19,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "cat-5",
    name: "Món canh & Lẩu",
    slug: "mon-canh-lau",
    description: "Nước dùng thanh ngọt, các món canh đưa cơm và lẩu sum họp cuối tuần.",
    recipeCount: 24,
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80",
  },
];

export interface ExtendedRecipeDto extends RecipeDto {
  rating: number;
  totalReviews: number;
  isFeatured?: boolean;
  categorySlug: string;
  summary: string;
  authorAvatar?: string;
  authorRole?: string;
}

export const MOCK_RECIPES: ExtendedRecipeDto[] = [
  {
    id: "rec-1",
    title: "Phở Bò Bắp Hoa Hà Nội Chuẩn Vị Gia Truyền",
    slug: "pho-bo-bap-hoa-ha-noi",
    summary: "Nước dùng thanh trong, thơm nức mùi hoa hồi, thảo quả quyện cùng bắp hoa tươi mềm và bánh phở dai ngon.",
    description: "Món phở truyền thống Hà Nội đòi hỏi sự kiên nhẫn trong khâu ninh xương để có được vị ngọt thanh tự nhiên mà không cần phụ gia. Kết hợp cùng gia vị thảo mộc mộc mạc làm nên hương vị khó quên.",
    primaryImageUrl: "/images/image 1.png",
    prepTimeMinutes: 30,
    cookTimeMinutes: 180,
    servings: 4,
    difficulty: "Medium",
    categoryName: "Món chính gia đình",
    categorySlug: "mon-chinh",
    authorName: "Đầu bếp Hoàng Nam",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    authorRole: "Chef ẩm thực Việt",
    createdAt: "2026-09-28T08:00:00Z",
    rating: 4.9,
    totalReviews: 128,
    isFeatured: true,
    likeCount: 342,
    isLiked: false,
    ingredients: [
      { id: "ing-1", name: "Xương ống bò", quantity: 1.5, unit: "kg", notes: "Chặt khúc vừa" },
      { id: "ing-2", name: "Bắp hoa bò", quantity: 500, unit: "g", notes: "Thái mỏng" },
      { id: "ing-3", name: "Bánh phở tươi", quantity: 800, unit: "g" },
      { id: "ing-4", name: "Hành tây, hành tím, gừng", quantity: 1, unit: "bộ", notes: "Nướng thơm" },
      { id: "ing-5", name: "Hoa hồi, thảo quả, quế, hạt ngò", quantity: 1, unit: "gói gia vị phở" },
      { id: "ing-6", name: "Hành lá, ngò gai, chanh, ớt tươi", quantity: 1, unit: "dĩa" },
    ],
    steps: [
      { id: "st-1", stepNumber: 1, description: "Sơ chế xương bò: Chần xương ống trong nước sôi có gừng giã dập khoảng 10 phút để loại bỏ tạp chất. Rửa lại thật sạch bằng nước lạnh.", durationMinutes: 15 },
      { id: "st-2", stepNumber: 2, description: "Ninh nước dùng: Cho xương vào nồi cùng 4 lít nước. Thêm hành tây, gừng nướng và túi gia vị thảo mộc. Ninh lửa nhỏ trong 3 tiếng, hớt bọt liên tục.", durationMinutes: 180 },
      { id: "st-3", stepNumber: 3, description: "Trình bày & Thưởng thức: Chần bánh phở qua nước sôi, xếp thịt bắp hoa thái mỏng lên trên, rắc hành lá ngò gai rồi chan nước dùng thật sôi.", durationMinutes: 10 },
    ],
  },
  {
    id: "rec-2",
    title: "Cơm Tấm Sườn Nướng Mật Ong Kim Chi",
    slug: "com-tam-suon-nuong-mat-ong",
    summary: "Miếng sườn cốt lết được ướp đậm đà gia vị thảo mộc và mật ong rừng, nướng xém cạnh mọng nước ăn kèm cơm tấm dẻo thơm.",
    description: "Bí quyết cho miếng sườn mềm ngọt không bị khô chính là nước ép hành tỏi và thời gian nghỉ sau khi nướng. Món ăn hòa quyện giữa vị mặn ngọt đậm đà và đồ chua thanh mát.",
    primaryImageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    prepTimeMinutes: 25,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Easy",
    categoryName: "Món chính gia đình",
    categorySlug: "mon-chinh",
    authorName: "Minh Thư Foodie",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    authorRole: "Home Cook",
    createdAt: "2026-09-27T10:30:00Z",
    rating: 4.8,
    totalReviews: 86,
    isFeatured: true,
    likeCount: 215,
    isLiked: true,
    ingredients: [
      { id: "ing-7", name: "Sườn cốt lết bò/heo", quantity: 600, unit: "g" },
      { id: "ing-8", name: "Mật ong nguyên chất", quantity: 2, unit: "muỗng canh" },
      { id: "ing-9", name: "Nước mắm ngon", quantity: 2, unit: "muỗng canh" },
      { id: "ing-10", name: "Dầu hào, sả băm, tỏi băm", quantity: 1, unit: "phần" },
      { id: "ing-11", name: "Gạo tấm thơm", quantity: 300, unit: "g" },
    ],
    steps: [
      { id: "st-4", stepNumber: 1, description: "Ướp thịt sườn với hỗn hợp mật ong, nước mắm, dầu hào và sả tỏi băm trong ít nhất 45 phút.", durationMinutes: 45 },
      { id: "st-5", stepNumber: 2, description: "Nướng thịt trên bếp than hoặc nồi chiên không dầu ở 180°C trong 15 phút, phết sốt ướp 2 lần.", durationMinutes: 20 },
      { id: "st-6", stepNumber: 3, description: "Dọn cơm tấm ra đĩa cùng mỡ hành, đồ chua, chả trứng và chén nước mắm tỏi ớt kẹo dẻo.", durationMinutes: 5 },
    ],
  },
  {
    id: "rec-3",
    title: "Salad Bơ Bơ Địa Trung Hải Thanh Đạm",
    slug: "salad-bo-dia-trung-hai",
    summary: "Sự kết hợp hoàn hảo giữa bơ chín dẻo, cà chua cherry ngào đường, hạt quinoa nướng và sốt chanh vàng sốt kem tươi mát.",
    description: "Món salad giàu chất béo tốt và chất xơ, thích hợp cho chế độ ăn Eat Clean lành mạnh mà vẫn đảm bảo độ ngon miệng tự nhiên.",
    primaryImageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 2,
    difficulty: "Easy",
    categoryName: "Món chay thanh tịnh",
    categorySlug: "mon-chay",
    authorName: "Linh Green Kitchen",
    authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    authorRole: "Nutrition Coach",
    createdAt: "2026-09-25T14:15:00Z",
    rating: 4.7,
    totalReviews: 45,
    isFeatured: false,
    likeCount: 189,
    isLiked: false,
    ingredients: [
      { id: "ing-12", name: "Bơ sáp chín", quantity: 2, unit: "quả", notes: "Cắt khối vừa ăn" },
      { id: "ing-13", name: "Cà chua cherry", quantity: 150, unit: "g", notes: "Cắt đôi" },
      { id: "ing-14", name: "Rau xà lách Rocket & Kale", quantity: 100, unit: "g" },
      { id: "ing-15", name: "Dầu olive Extra Virgin", quantity: 2, unit: "muỗng canh" },
      { id: "ing-16", name: "Nước cốt chanh vàng & Muối biển", quantity: 1, unit: "ít" },
    ],
    steps: [
      { id: "st-7", stepNumber: 1, description: "Rửa sạch rau củ, để ráo nước hoàn toàn.", durationMinutes: 10 },
      { id: "st-8", stepNumber: 2, description: "Pha sốt dressing: Trộn đều dầu olive, nước chanh vàng, chút muối và tiêu đen xay.", durationMinutes: 5 },
      { id: "st-9", stepNumber: 3, description: "Trộn nhẹ các nguyên liệu trong thố lớn, tưới sốt ngay trước khi ăn.", durationMinutes: 5 },
    ],
  },
  {
    id: "rec-4",
    title: "Bánh Matcha Mousse Nhật Bản Mềm Mịn",
    slug: "banh-matcha-mousse-nhat-ban",
    summary: "Lớp mousse matcha Uji béo ngậy đắng nhẹ kết hợp với đế bánh gato socola đắng thanh lịch.",
    description: "Bánh lạnh sang trọng, công thức tinh chỉnh ngọt nhẹ phù hợp cho các buổi tiệc trà chiều hoặc quà tặng người thân.",
    primaryImageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
    prepTimeMinutes: 40,
    cookTimeMinutes: 15,
    servings: 6,
    difficulty: "Medium",
    categoryName: "Bánh & Tráng miệng",
    categorySlug: "banh-ngot",
    authorName: "Chef Bakery An",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    authorRole: "Pastry Chef",
    createdAt: "2026-09-24T16:00:00Z",
    rating: 4.9,
    totalReviews: 92,
    isFeatured: true,
    likeCount: 410,
    isLiked: false,
    ingredients: [
      { id: "ing-17", name: "Bột trà xanh Matcha Uji", quantity: 15, unit: "g" },
      { id: "ing-18", name: "Whipping cream 35%", quantity: 300, unit: "ml" },
      { id: "ing-19", name: "Gelatin lá", quantity: 8, unit: "g" },
      { id: "ing-20", name: "Đường xay", quantity: 60, unit: "g" },
      { id: "ing-21", name: "Sữa tươi không đường", quantity: 100, unit: "ml" },
    ],
    steps: [
      { id: "st-10", stepNumber: 1, description: "Ngâm lá gelatin trong nước lạnh 10 phút. Đun ấm sữa tươi rồi hòa tan bột matcha và gelatin.", durationMinutes: 15 },
      { id: "st-11", stepNumber: 2, description: "Đánh bông nhẹ whipping cream với đường, từ từ trộn hỗn hợp matcha lạnh vào theo phương pháp fold.", durationMinutes: 15 },
      { id: "st-12", stepNumber: 3, description: "Rót mousse vào khuôn ring, để tủ lạnh ngăn mát ít nhất 4 tiếng trước khi thưởng thức.", durationMinutes: 240 },
    ],
  },
  {
    id: "rec-5",
    title: "Trà Hoa Cúc Mật Ong Hạt Chia Giải Nhiệt",
    slug: "tra-hoa-cuc-mat-ong-hat-chia",
    summary: "Thức uống thảo mộc giúp thư giãn tinh thần, thanh lọc cơ thể và đẹp da tự nhiên.",
    description: "Hoa cúc sấy lạnh giữ trọn hương thơm thanh khiết, kết hợp cùng ngọt dịu của mật ong nhãn và hạt chia mát lành.",
    primaryImageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    servings: 2,
    difficulty: "Easy",
    categoryName: "Đồ uống & Pha chế",
    categorySlug: "do-uong",
    authorName: "Linh Green Kitchen",
    authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    authorRole: "Nutrition Coach",
    createdAt: "2026-09-22T09:00:00Z",
    rating: 4.6,
    totalReviews: 31,
    isFeatured: false,
    likeCount: 95,
    isLiked: false,
    ingredients: [
      { id: "ing-22", name: "Hoa cúc khô vàng", quantity: 10, unit: "g" },
      { id: "ing-23", name: "Mật ong nhãn", quantity: 2, unit: "muỗng canh" },
      { id: "ing-24", name: "Hạt chia hữu cơ", quantity: 1, unit: "muỗng canh" },
      { id: "ing-25", name: "Nước nóng 90°C", quantity: 500, unit: "ml" },
    ],
    steps: [
      { id: "st-13", stepNumber: 1, description: "Ủ hoa cúc trong nước nóng 8 phút để chiết xuất hương vị.", durationMinutes: 8 },
      { id: "st-14", stepNumber: 2, description: "Lọc bỏ xác hoa, thêm mật ong và hạt chia vào khuấy đều.", durationMinutes: 3 },
      { id: "st-15", stepNumber: 3, description: "Thêm đá viên hoặc uống ấm tùy sở thích.", durationMinutes: 2 },
    ],
  },
  {
    id: "rec-6",
    title: "Lẩu Nấm Thảo Mộc Chay Chua Cay",
    slug: "lau-nam-thao-moc-chay",
    summary: "Nước lẩu ninh từ củ quả ngọt đậm đà, thơm lừng vị sả ớt, lá chanh ăn kèm các loại nấm tươi giòn sần sật.",
    description: "Bữa tiệc lẩu chay đầm ấm cùng gia đình, kết hợp nấm kim针, nấm đùi gà, nấm hải sản và đậu hũ non chiên vàng.",
    primaryImageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    prepTimeMinutes: 25,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    categoryName: "Món canh & Lẩu",
    categorySlug: "mon-canh-lau",
    authorName: "Minh Thư Foodie",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    authorRole: "Home Cook",
    createdAt: "2026-09-20T11:00:00Z",
    rating: 4.8,
    totalReviews: 54,
    isFeatured: false,
    likeCount: 167,
    isLiked: false,
    ingredients: [
      { id: "ing-26", name: "Các loại nấm tươi", quantity: 600, unit: "g" },
      { id: "ing-27", name: "Củ sắn, bắp ngọt, cà rốt", quantity: 1, unit: "bộ ninh nước" },
      { id: "ing-28", name: "Sả cây, ớt, riềng, lá chanh", quantity: 1, unit: "bộ gia vị lẩu" },
      { id: "ing-29", name: "Đậu hũ non", quantity: 2, unit: "hộp" },
    ],
    steps: [
      { id: "st-16", stepNumber: 1, description: "Ninh củ sắn, bắp ngọt trong 30 phút lấy nước ngọt tự nhiên.", durationMinutes: 30 },
      { id: "st-17", stepNumber: 2, description: "Phi thơm sả riềng, trút vào nồi nước lẩu cùng sốt lẩu thái chay và nêm vừa vị.", durationMinutes: 10 },
      { id: "st-18", stepNumber: 3, description: "Bày các loại nấm, rau nhúng lẩu và thưởng thức nóng trên bếp lẩu.", durationMinutes: 5 },
    ],
  },
];
